export const CANAUX = {
  diagnostic: {
    obtenirVersions: 'diagnostic.obtenirVersions',
  },
  parametres: {
    lire: 'parametres.lire',
    lireSeuilEspeces: 'parametres.lireSeuilEspeces',
  },
  bareme: {
    lister: 'bareme.lister',
  },
  exercices: {
    courant: 'exercices.courant',
  },
  familles: {
    lister: 'familles.lister',
  },
  clients: {
    lister: 'clients.lister',
    creer: 'clients.creer',
    lire: 'clients.lire',
    modifier: 'clients.modifier',
    supprimer: 'clients.supprimer',
    creerContact: 'clients.creerContact',
    listerContacts: 'clients.listerContacts',
    modifierContact: 'clients.modifierContact',
    supprimerContact: 'clients.supprimerContact',
    creerInteraction: 'clients.creerInteraction',
    listerInteractions: 'clients.listerInteractions',
    supprimerInteraction: 'clients.supprimerInteraction',
    calculerScore: 'clients.calculerScore',
  },
  encaissements: {
    lister: 'encaissements.lister',
    creer: 'encaissements.creer',
    supprimer: 'encaissements.supprimer',
    modifierTimbre: 'encaissements.modifierTimbre',
  },
  session: {
    etat: 'session.etat',
    premierDemarrage: 'session.premierDemarrage',
    deverrouiller: 'session.deverrouiller',
    verrouiller: 'session.verrouiller',
    changerMotDePasse: 'session.changerMotDePasse',
    activite: 'session.activite',
  },
  sauvegarde: {
    archiver: 'sauvegarde.archiver',
    restaurer: 'sauvegarde.restaurer',
    lister: 'sauvegarde.lister',
    appliquerRetention: 'sauvegarde.appliquerRetention',
    nommer: 'sauvegarde.nommer',
  },
  journal: {
    ecrire: 'journal.ecrire',
    lire: 'journal.lire',
    exporter: 'journal.exporter',
  },
  tarifs: {
    creer: 'tarifs.creer',
    lister: 'tarifs.lister',
    listerParProduit: 'tarifs.listerParProduit',
    listerParClient: 'tarifs.listerParClient',
    listerParAffaire: 'tarifs.listerParAffaire',
    supprimer: 'tarifs.supprimer',
  },
  produits: {
    creer: 'produits.creer',
    lister: 'produits.lister',
    lire: 'produits.lire',
    modifier: 'produits.modifier',
    supprimer: 'produits.supprimer',
    listerParFamille: 'produits.listerParFamille',
  },
  sousFamilles: {
    creer: 'sousFamilles.creer',
    lister: 'sousFamilles.lister',
    listerParFamille: 'sousFamilles.listerParFamille',
    supprimer: 'sousFamilles.supprimer',
  },
  classifications: {
    creer: 'classifications.creer',
    lister: 'classifications.lister',
    modifier: 'classifications.modifier',
  },
  affaires: {
    lister: 'affaires.lister',
    creer: 'affaires.creer',
    lire: 'affaires.lire',
    modifier: 'affaires.modifier',
    supprimer: 'affaires.supprimer',
  },
  devis: {
    lister: 'devis.lister',
    creer: 'devis.creer',
    lire: 'devis.lire',
    modifier: 'devis.modifier',
    supprimer: 'devis.supprimer',
    creerLigne: 'devis.creerLigne',
    listerLignes: 'devis.listerLignes',
    supprimerLigne: 'devis.supprimerLigne',
  },
  postesDqe: {
    listerParAffaire: 'postesDqe.listerParAffaire',
    creer: 'postesDqe.creer',
    modifier: 'postesDqe.modifier',
    supprimer: 'postesDqe.supprimer',
  },
  avenants: {
    listerParAffaire: 'avenants.listerParAffaire',
    creer: 'avenants.creer',
    modifierStatut: 'avenants.modifierStatut',
    supprimer: 'avenants.supprimer',
    creerPoste: 'avenants.creerPoste',
    listerPostes: 'avenants.listerPostes',
  },
  evenementsDelais: {
    listerParAffaire: 'evenementsDelais.listerParAffaire',
    creer: 'evenementsDelais.creer',
    supprimer: 'evenementsDelais.supprimer',
  },
  import: {
    lireFichier: 'import.lireFichier',
    validerLignes: 'import.validerLignes',
    executer: 'import.executer',
  },
  factures: {
    lister: 'factures.lister',
    creer: 'factures.creer',
    lire: 'factures.lire',
    modifier: 'factures.modifier',
    supprimer: 'factures.supprimer',
    valider: 'factures.valider',
    calculerPied: 'factures.calculerPied',
    listerLignes: 'factures.listerLignes',
    creerLigne: 'factures.creerLigne',
    modifierLigne: 'factures.modifierLigne',
    supprimerLigne: 'factures.supprimerLigne',
    genererPdf: 'factures.genererPdf',
    imprimer: 'factures.imprimer',
    marquerEnvoyee: 'factures.marquerEnvoyee',
    creerAvoir: 'factures.creerAvoir',
    listerAvoirs: 'factures.listerAvoirs',
  },
  bonsLivraison: {
    lister: 'bonsLivraison.lister',
    creer: 'bonsLivraison.creer',
    lire: 'bonsLivraison.lire',
    modifier: 'bonsLivraison.modifier',
    supprimer: 'bonsLivraison.supprimer',
    listerLignes: 'bonsLivraison.listerLignes',
    creerLigne: 'bonsLivraison.creerLigne',
    modifierLigne: 'bonsLivraison.modifierLigne',
    supprimerLigne: 'bonsLivraison.supprimerLigne',
    genererFacture: 'bonsLivraison.genererFacture',
  },
} as const
