export const CANAUX = {
  diagnostic: {
    obtenirVersions: 'diagnostic.obtenirVersions',
  },
  parametres: {
    lire: 'parametres.lire',
    lireSeuilEspeces: 'parametres.lireSeuilEspeces',
  },
  bareme: {
    lister: 'bareme.lister',
  },
  exercices: {
    courant: 'exercices.courant',
  },
  familles: {
    lister: 'familles.lister',
  },
  clients: {
    lister: 'clients.lister',
    creer: 'clients.creer',
    lire: 'clients.lire',
    modifier: 'clients.modifier',
    supprimer: 'clients.supprimer',
    creerContact: 'clients.creerContact',
    listerContacts: 'clients.listerContacts',
    modifierContact: 'clients.modifierContact',
    supprimerContact: 'clients.supprimerContact',
    creerInteraction: 'clients.creerInteraction',
    listerInteractions: 'clients.listerInteractions',
    supprimerInteraction: 'clients.supprimerInteraction',
    calculerScore: 'clients.calculerScore',
  },
  encaissements: {
    lister: 'encaissements.lister',
    creer: 'encaissements.creer',
    supprimer: 'encaissements.supprimer',
    modifierTimbre: 'encaissements.modifierTimbre',
  },
  session: {
    etat: 'session.etat',
    premierDemarrage: 'session.premierDemarrage',
    deverrouiller: 'session.deverrouiller',
    verrouiller: 'session.verrouiller',
    changerMotDePasse: 'session.changerMotDePasse',
    activite: 'session.activite',
  },
  sauvegarde: {
    archiver: 'sauvegarde.archiver',
    restaurer: 'sauvegarde.restaurer',
    lister: 'sauvegarde.lister',
    appliquerRetention: 'sauvegarde.appliquerRetention',
    nommer: 'sauvegarde.nommer',
  },
  journal: {
    ecrire: 'journal.ecrire',
    lire: 'journal.lire',
    exporter: 'journal.exporter',
  },
  tarifs: {
    creer: 'tarifs.creer',
    lister: 'tarifs.lister',
    listerParProduit: 'tarifs.listerParProduit',
    listerParClient: 'tarifs.listerParClient',
    listerParAffaire: 'tarifs.listerParAffaire',
    supprimer: 'tarifs.supprimer',
  },
  produits: {
    creer: 'produits.creer',
    lister: 'produits.lister',
    lire: 'produits.lire',
    modifier: 'produits.modifier',
    supprimer: 'produits.supprimer',
    listerParFamille: 'produits.listerParFamille',
  },
  sousFamilles: {
    creer: 'sousFamilles.creer',
    lister: 'sousFamilles.lister',
    listerParFamille: 'sousFamilles.listerParFamille',
    supprimer: 'sousFamilles.supprimer',
  },
  classifications: {
    creer: 'classifications.creer',
    lister: 'classifications.lister',
    modifier: 'classifications.modifier',
  },
  import: {
    lireFichier: 'import.lireFichier',
    validerLignes: 'import.validerLignes',
    executer: 'import.executer',
  },
} as const
